apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sample-pod-monitor
  namespace: custom-apps
spec:
  selector:
    matchLabels:
      app: sample-app
  podMetricsEndpoints:
  - port: metrics
    interval: 30s

